Mobile search
1Hive/honey-pot pull request #95
Opened 2020-10-02 01:00 UTC by anthonyoliai

Simple mobile search, one small bug is that the margins are still in place when the screen gets really small so it's not perfectly aligned. This is due to the nature of flex-wrap. Right now the dropdowns work, and the search bar is a popover. Can make it so that it's already an extended bar if suggested. I just thought it would look cleaner this way.

2020-10-02 12:37 UTC, rperez89 requested changes
Hey man! thxs! could you please share some screenshots to see how it looks likes? we should ask @fioreb about a desing for this, also cc @fabriziovigevani i remember that there were some design guideline or something about this because in any aragon app we have search bar on mobile view

2020-10-02 14:07 UTC, fioreb commented
Thanks!

Filters and search bar were designed by the Aragon1 team but the implementation was left for later, for the moment in mobile devices we don't have filters of any type because of that.

Since we are going to change for a Feed in Honey Pot version 2, I add the filters to the designs but we don't have a search bar. Here you can check the designs: https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=461%3A7943

I think that if we are going to add the search bar now, we can put it always displayed as we have it on desktop

2020-10-02 14:16 UTC, anthonyoliai commented
Sounds great! Thanks for the review and replies. I've mostly just reused the same components for the FilterBar that were already in place, to prevent any design inconsistencies. 
![2aad6c8c9df0711221b6ef004e58cd41](https://user-images.githubusercontent.com/61785803/94933340-8bc85900-04ca-11eb-9681-d0a18786b69d.png)
Perhaps it's better to just remove the popover in the mobile version and have it already be an expanded search bar.

2020-10-02 14:48 UTC, fioreb commented
Great, thanks for that!

Yes, I think that have it already as an expanded search bar would be nice!

2020-10-02 18:30 UTC, anthonyoliai commented
Alright! I did what I could :) (Still learning how React works..). What I did is use a negative margin-left on the parent div to fix the flex-wrapping problem, which caused the dropdown filters not to be aligned when wrapping due to a small width. Two examples given: normal mobile width, very small mobile width:
![screenshot1](https://user-images.githubusercontent.com/61785803/94957439-0bb3ea80-04ee-11eb-85fa-69b6afc67d1b.png)
![screenshot2](https://user-images.githubusercontent.com/61785803/94957445-0ce51780-04ee-11eb-9232-2ce15d2c9a8b.png)
Search functionality works :)

2020-10-05 18:17 UTC, fabriziovigevani reviewed
Nicely done @anthonyoliai !

Left some comments

Was also wondering if we should use some bottom margin between filters when they are stacked?

2020-10-05 18:17 UTC, fabriziovigevani commented on src/components/FilterBar/TextFilter.js
>      const { layoutName } = useLayout()
I think we should remove this one :)

2020-10-05 18:17 UTC, fabriziovigevani commented on src/components/FilterBar/TextFilter.js
> -    onClick,
Since we are removing this props, we should also remove them from the declared `PropTypes` below

2020-10-06 23:42 UTC, anthonyoliai commented
Applied the changes, search filters indeed look nicing with bottom margin. Also cleaned the overall code! Please have a look :) Let me know if more changes are necessary.

2020-10-07 14:06 UTC, fabriziovigevani reviewed
Looks good!

We missed to add the same bottom margin to the `DropwdownFilter` which is displayed conditionally from the proposal status filter (Removed or Closed).


![Screen Shot 2020-10-07 at 11 02 35 AM](https://user-images.githubusercontent.com/22663232/95341828-1a532680-088d-11eb-8a39-70210d3af50a.png)

Lets add that and LGTM!

2020-10-07 14:35 UTC, fabriziovigevani approved these changes
LGTM! Thanks!

2020-10-07 14:36 UTC, merged